### ISSUE TITLE
Cannot add new definitions through AuthoringTool

### ISSUE THREAD

**Issue by FedeDP** [ishkin/Proton#31]
Hi,

I'm having this issue with proton. I run it through docker. Every time i try to export my Project to the defined folder through AuthoringTool webapp, i receive a java.lang.NullPointerException.
Log: http://codepad.org/nfmfNztm .
And obviously, nothing works.

I only followed the instructions to build my docker image and run it. Tomcat7 service is up and running.
Any idea?

Thank you very much!

**Comment by ishkin** [comment]
Usually this problem is an indication that the definition repository for Authoring Tool is not defined properly. 
Pls see instructions here: https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/CEP_GE_-_IBM_Proactive_Technology_Online_Installation_and_Administration_Guide
(under Configuring the administration application)
In case this doesn't help, please open an issue for the GE using the regular FIWARE channels (I assume you are working with Proton in the scrope of FIWARE project? )

**Comment by FedeDP** [comment]
I'm using the docker file (as previously stated) and i checked all of the options. They've got the right value (i mean, the docker image is preconfigured, as far as i can tell).
But, eg, yesterday i found out a way to make it work: i had to manually copy/paste my own json to a Test.json inside the /var/lib/tomcat7/webapps/ProtonOnWebServer/ folder, then softlink /var/lib/tomcat7/webapps to /usr/share/tomcat7 and change Proton.properties, that is where tomcat is expected to live (as it was told by the logs).
This way, i could make my proton instance do its job.

Yes, i'm working on a FIWARE project.
I'll post a mail to the regular channel then.
Thanks.
